version: "3.0"
services:
  backend:
    build: .
    env_file: .env
    ports:
      - "8080:8080/tcp"
    restart: always
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - "~/autoparts-db:/var/lib/postgresql/data:rw"
